extends Node

var enums = preload("res://Global/globalEnums.gd")

const WIDTH = 50
const HEIGHT = 35

func GetAscii():
	var output = String(ascii)
	output = output.replace(" ", "")
	output = output.replace("\n", "")
	return output

var buildingsStart = [enums.BUILDING_TYPE.BOOTH_PRODUCE, enums.BUILDING_TYPE.BLACKSMITH, enums.BUILDING_TYPE.ROAD]
var researchStart = [enums.RESEARCH.BUILD_BOOTH_PRODUCE, enums.RESEARCH.BUILD_BLACKSMITH]
var researchNext = [enums.RESEARCH.BUILD_TAVERN, enums.RESEARCH.BUILD_BATH]


const ascii = """
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT-T-T-TTT-TTTTTTTTTT
TTTTTTTT-TTTTTTSSTTTTTTTTTTTTTTTTTTTTTT-TTTTTTTTTT
TT-TTTTTTTT--SSSS----------TTTTTT-----TTTTTTTTTTTT
TTTTTTTTTT--SSSS------------------SS--TTTTTTTTTTTT
TTTTTTTT--SSSSS----DDDDDDDDDDD-------------TTTTTTT
TTTTTTTT--------DDDDDDDDDDDDDDDDDDDDDDSSSSSSS--TT-
TTTTTT-T------DDDDD--------DDDDDDDDDDDDDD---------
TTTTTTTT-----DDD-----T---------------DDDDDDD------
TTTTTT-----DDDD----TTTTT----------------DDDDDDD---
----------DDDD----TT-T-T-----TTT-TTSSS------DDDDD2
-SS----DDDDD-----TTTTT-T------TTTTTTT-SS-----DDDD2
-----DDDDD-------TTTTT-T--------TTTTTTT-----DDDDD2
----DDDDDDDD----TTTTTT-TT--DDDD---TTTTT----DD-S-SS
-DDDDD-----DD--T-TTTTT-TT-----DD---TTS----DD------
1DDD---SS---DD-T-TTTTTT-TT-----DD-------DDD----SS-
1DD---SSSS---DDTTTTTTT-TTTT-----DD----DDD---S--SSS
SS-----SS-T-TTDDTTTTTTTT---------DD-DDD----SSS--SS
SSSS----T-TTTTTDTT--T--T-SSSSS---DDDD---SS------TS
-S-----TTTTT-T-DDTTTTTTTTT-------DD----S------TTTT
----TTTT-TTTTTTTD-----TTTTTT-----DD---------TTTTTT
---TTTTTTTTTTTT-D--------TTT--DDDDDD-------TTTTTTT
-------TTTTT----DDDDDDD------DD----DDD--TTTTTTTTTT
-S-SS---TTTS---DD-----DDDDDDDD----TTDDDTTTTTTTTTTT
-------TTTSS--DD---T------------TTTTTTDDDTTTTTTT-T
4DD--S-TTTSS-DD---TT--TTTTTTTTTTTTT-T-TDDDTTTTTTTT
--DDD---TT---D----TTTTTTTTTTT-TT--T-TTTTTDDDTT-TTT
----DDDDD----D--TTTTTTT-TTTWWTTTT-TTTTTT-TTDDTTT--
--------DDDDDD--TTTT-TTTTWWWWWW-T-TTTTTTTTTDDD----
--TTTT--SS------TTTTTTTWWWWT-TTTTTT--T--TT--DD----
-TTTT--SSSS---TTTTTTTTWWT-TTTTT-TTTTTTTTT---DD----
TTTT-WWWWWWWTTT-TT-TTT-T-TT-TTTTT-----------DD----
TTT-TTTTWWWWTWWTTTTT--TTTTTTTT------------DDDD----
TTTTTTTWWWWWWWWTTTTTTTTT-TTT--------------DD------
TTTTTTTTWWTTTTTTTTTTTTTTTTT---------------333-----
"""



