extends Node

enum CLICK_TYPE { TREE, STONE }

enum TILETYPE { GRASS, WATER, TREE, DIRT}

const TILE_SIZE_PIXELS = 32

const NUM_TREE_SPRITES = 6

enum TILE_SHAPE { EMPTY, HORIZONTAL, VERTICAL, UP_LEFT, UP_RIGHT, DOWN_RIGHT, DOWN_LEFT, RIGHT_T, DOWN_T, LEFT_T, UP_T, INTERSECTION }

enum MODE { NORMAL, BUILD }

enum MOUSE_STATE { NONE, INSIDE, OUTSIDE }
